name: CI-test

env:
  GITHUB_ACTIONS: true

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "**.md"
      - "LICENSE"

  pull_request:
    branches: ["main"]
    paths-ignore:
      - "**.md"
      - "LICENSE"

  workflow_dispatch:

jobs:
  CI:
    strategy:
      matrix:
        os-version: ["windows-latest", "ubuntu-latest", "macos-14"]
        python-version: ["3.9"]
        pytorch-version: ["2.7.1", "2.1.2", "2.0.0", "1.13.0"]

    runs-on: ${{ matrix.os-version }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: |
          uv sync

      - name: Install PyTorch 2.7.1
        if: matrix.pytorch-version == '2.7.1'
        run: |
          uv pip install torch==2.7.1 torchvision==0.22.1 torchaudio==2.7.1

      - name: Install PyTorch 2.1.2
        if: matrix.pytorch-version == '2.1.2'
        run: |
          uv pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2

      - name: Install PyTorch 2.0.0
        if: matrix.pytorch-version == '2.0.0'
        run: |
          uv pip install torch==2.0.0 torchvision==0.15.1 torchaudio==2.0.1

      - name: Install PyTorch 1.13.0
        if: matrix.pytorch-version == '1.13.0'
        run: |
          uv pip install torch==1.13.0 torchvision==0.14.0 torchaudio==0.13.0

      - name: Show environment
        run: |
          uv python -m pip list

      - name: Test
        run: |
          make lint
          make test

      - name: Codecov
        if: matrix.os-version == 'ubuntu-latest' && matrix.python-version == '3.9' && matrix.pytorch-version == '2.7.1'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
